import { query } from "@anthropic-ai/claude-agent-sdk";
import { Resend } from "resend";
import { execSync } from "child_process";

const BRANCH = `blog/auto-${new Date().toISOString().slice(0,10)}`;
const TEMPLATE_URL = "https://jordanshapiro555-lab.github.io/CRO-Consulting/blog/";

// Create branch
execSync(`git config user.name "CRO Bot" && git config user.email "bot@cro-studio.dev"`);
execSync(`git checkout -b ${BRANCH}`);

const systemPrompt = `You are an orchestrator running a 7-stage CRO blog pipeline for Jordan's CRO Studio.

REPO LAYOUT: Blog posts live in /blog/ as HTML files. Use an existing post in /blog/ as your structural template — copy it, then replace content.

STAGES (run sequentially, each as a separate subagent task):
1. RESEARCHER: Use WebSearch to find 5-8 recent CRO trends/studies/news from the last 30 days. Cite sources (Baymard, NNG, CXL, ConversionXL, GoodUI, etc.). Output: research-notes.md
2. OUTLINER: Read research-notes.md. Produce a blog outline with H2/H3 structure, target keyword, angle, and reader takeaway. Output: outline-v1.md
3. CRITIC: Review outline-v1.md against: novelty, SEO opportunity, demonstration of Jordan's expertise (CRO + SEO + content strategy), reader engagement. Output: critique.md with specific improvements.
4. REVISER: Apply critique to produce outline-v2.md.
5. WRITER: Write the full blog post (~1200-1800 words) in markdown. Strong hook, scannable sections, data citations, concrete examples, clear CTA. Output: post-draft.md
6. DEVELOPER: Read /blog/ directory. Pick the most recent post as a structural template. Create a new HTML file in /blog/ following the same structure, classes, and styling. Inject the post content. Update /blog/index.html if it has a post listing.
7. SEO OPTIMIZER: Audit the new HTML for: title tag (50-60 chars), meta description (150-160), H1, semantic headings, alt text, internal links to other /blog/ posts, schema.org Article JSON-LD, keyword in URL/title/H1/first paragraph. Fix issues directly in the HTML.
8. QA: Verify HTML validates, links work, no Lorem ipsum, word count in range, all images have alt, meta tags present. Output: qa-report.md. If any check fails, fix it.

After all stages: list final files created/modified in <output> tags.`;

let finalOutput = "";
for await (const msg of query({
  prompt: `Run the full pipeline. Today's date: ${new Date().toDateString()}. Template reference: ${TEMPLATE_URL}`,
  options: {
    systemPrompt,
    allowedTools: ["Read", "Write", "Edit", "Glob", "Grep", "WebSearch", "WebFetch", "Bash"],
    permissionMode: "bypassPermissions",
    maxTurns: 80,
  },
})) {
  if (msg.type === "assistant") {
    for (const block of msg.message.content) {
      if (block.type === "text") {
        finalOutput += block.text;
        console.log(block.text);
      }
    }
  }
}

// Commit + push + PR
execSync(`git add -A`);
execSync(`git commit -m "New CRO blog post (auto-generated draft)"`);
execSync(`git push origin ${BRANCH}`);

const prUrl = execSync(
  `gh pr create --title "Auto blog draft: ${BRANCH}" --body "Generated by CRO Blog Pipeline. Review the new post in /blog/ and the QA report." --base main --head ${BRANCH}`,
  { env: { ...process.env, GH_TOKEN: process.env.GITHUB_TOKEN } }
).toString().trim();

// Email notification
const resend = new Resend(process.env.RESEND_API_KEY);
await resend.emails.send({
  from: "onboarding@resend.dev",
  to: process.env.NOTIFY_EMAIL,
  subject: `📝 New CRO blog draft ready for review — ${BRANCH}`,
  html: `
    <h2>Your CRO blog draft is ready</h2>
    <p><strong>Branch:</strong> ${BRANCH}</p>
    <p><strong>Review the PR:</strong> <a href="${prUrl}">${prUrl}</a></p>
    <p>Pipeline stages completed: Research → Outline → Critique → Revise → Write → Develop → SEO → QA</p>
    <hr>
    <pre style="font-size:12px;white-space:pre-wrap">${finalOutput.slice(-2000)}</pre>
  `,
});

console.log(`✅ Done. PR: ${prUrl}`);
